version: "2"
linters:
  enable:
    - dupl
  settings:
    dupl:
      threshold: 100
  exclusions:
    rules:
      - linters:
          - dupl
        path: _test\.go
      - linters:
          - dupl
        path: tests/
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
